//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrantikAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetailsPayment
    {
        public long Id { get; set; }
        public long PaymentId { get; set; }
        public long BookingDetailsId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string PaymentFor { get; set; }
    
        public virtual BookingDetail BookingDetail { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
