//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrantikAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public long Id { get; set; }
        public Nullable<long> BookingDetailsId { get; set; }
        public int MenuId { get; set; }
        public short Quantity { get; set; }
        public decimal Price { get; set; }
        public System.DateTime OrderExpectedDeliveryDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.TimeSpan OrderExpectedDeliveryTime { get; set; }
    
        public virtual BookingDetail BookingDetail { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
