//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrantikAPI.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.BookingDetailsPayments = new HashSet<BookingDetailsPayment>();
        }
    
        public long Id { get; set; }
        public decimal Amount { get; set; }
        public short PaymentModeId { get; set; }
        public string AdditionalDetails { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual MasterPaymentMode MasterPaymentMode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingDetailsPayment> BookingDetailsPayments { get; set; }
    }
}
