//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrantikAPI.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrantikEntities : DbContext
    {
        public PrantikEntities()
            : base("name=PrantikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingDetail> BookingDetails { get; set; }
        public virtual DbSet<BookingDetailsUser> BookingDetailsUsers { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomBooking> RoomBookings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<MasterPaymentMode> MasterPaymentModes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
    }
}
